Repository wecode-bootcamp-korea/38-1st-WESH-Korea-frontend, pull requests merged in 2022-10, with the labels that each got.

#2 [38기 정관훈]ADD: Nav
  public/data/data.json
  src/App.js
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Navcategory.js
  src/components/Nav/Navcategory.scss
  src/index.js
Labels: 멘토 리뷰 요청, 리뷰 진행 중

#8 [38기 정관훈]ADD: mainpage 레이아웃
  public/data/mainpage/best.json
  public/data/mainpage/main.json
  src/App.js
  src/Router.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/MainPage/Best.js
  src/pages/MainPage/Best.scss
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/ThumbNail.js
  src/pages/MainPage/ThumbNail.scss
Labels: 완료

#6 [38기 최규흠] ADD : Signin page fundamental features and layout
  src/Router.js
  src/pages/Join/SignIn/SignIn.js
  src/pages/Join/SignIn/SignIn.scss
Labels: 완료

#5 [38기 최규흠] ADD : Signup page fundamental features and layout
  public/data/login.json
  src/Router.js
  src/pages/Join/SignUp/SignUp.js
  src/pages/Join/SignUp/SignUp.scss
  src/styles/common.scss
Labels: 완료

#9 [38기 최우종] ADD : Footer
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 수정 요청

#19 [38기 정관훈]ADD: config
  src/config.js
Labels: 완료

#18 [38기 정관훈]ADD: 라우터 최종
  src/Router.js
Labels: 멘토 리뷰 요청

#4 [38기 정관훈]FIX: 상품리스트 기능 구현
  package-lock.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Search.js
  src/config.js
  src/pages/MainPage/Best.js
  src/pages/MainPage/MainPage.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductInfo.js
  src/pages/ProductDetail/ProductReview.js
  src/pages/ProductDetail/ProductTab.js
  src/pages/ProductDetail/ReviewList.js
  src/pages/ProductList/Banner.js
  src/pages/ProductList/Banner.scss
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/Product/Tag.js
  src/pages/ProductList/Product/Tag.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 완료

#13 [38기 정관훈]FIX: 상세페이지 기능 구현
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductInfo.js
  src/pages/ProductDetail/ProductReview.js
  src/pages/ProductDetail/ProductTab.js
  src/pages/ProductDetail/ProductTab.scss
  src/pages/ProductDetail/ReviewList.js
  src/pages/ProductDetail/ReviewList.scss
Labels: 멘토 리뷰 요청

#21 [38기 정관훈]ADD: 메인페이지 API 수정입니다.
  src/pages/MainPage/MainPage.js
Labels: 멘토 리뷰 요청

#15 [38기 최규흠]ADD:feature/signin 브랜치 nav바, navigate 추가
  src/pages/Join/SignIn/SignIn.js
  src/pages/Join/SignIn/SignIn.scss
  src/pages/Join/SignUp/SignUp.js
Labels: 완료

#20 [38기 정관훈]ADD: NAV 검색 기능 추가입니다..
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Navcategory.js
  src/components/Nav/Search.js
  src/components/Nav/Search.scss
  src/config.js
Labels: 멘토 리뷰 요청

#22 [38기 이다영]ADD: 장바구니 기능
  package-lock.json
  package.json
  public/data/cart.json
  public/images/profile.png
  src/Router.js
  src/components/Nav/Search.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Menutab/Mypage.js
  src/pages/Cart/Menutab/Mypage.scss
  src/pages/Cart/Menutab/Normal.js
  src/pages/Cart/Menutab/Normal.scss
  src/pages/Cart/Orderlist/Orderlist.js
  src/pages/Cart/Orderlist/Orderlist.scss
Labels: 멘토 리뷰 요청

#23 Feature/all
  public/data/cart.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Search.js
  src/pages/Cart/Menutab/Mypage.scss
  src/pages/Cart/Menutab/Normal.scss
  src/pages/Join/SignIn/SignIn.js
  src/pages/Join/SignIn/SignIn.scss
  src/pages/Join/SignUp/SignUp.js
  src/pages/Join/SignUp/SignUp.scss
  src/pages/MainPage/Best.js
  src/pages/MainPage/MainPage.js
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/ThumbNail.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductInfo.js
  src/pages/ProductDetail/ProductInfo.scss
  src/pages/ProductDetail/ProductTab.js
  src/pages/ProductDetail/ProductTab.scss
  src/pages/ProductDetail/ReviewList.js
  src/pages/ProductDetail/ReviewList.scss
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/Product/Tag.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청
